export const ROUTES = {
  index: "/",
  auth: "/auth",
  write: "/write",
  new: "/new",
  terms: "/terms",
  blog: "/blog",
  dashboard: "/dashboard",
  settings: "/settings",
  feedback: "/feedback",
  signIn: "/sign-in",
  signUp: "/sign-up",
  publishedURL: "https://pingu-blog.vercel.app",
  socials: { twitter: "https://x.com/pingulabs_" },
};
